spring:
  cloud:
    config:
      discovery:
        enabled: true
      enabled: false
      application:
        name: application
  datasource:
    url: jdbc:mysql://localhost:3306/ReparationBd?createDatabaseIfNotExist=true
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate: 
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
